--------------------------------------------------------
--  Arquivo criado - domingo-fevereiro-17-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TB_SWING_TRADE
--------------------------------------------------------

  CREATE TABLE "TB_SWING_TRADE" ("CODNEG" VARCHAR2(20))
REM INSERTING into TB_SWING_TRADE
SET DEFINE OFF;
Insert into TB_SWING_TRADE (CODNEG) values ('ABEV3');
Insert into TB_SWING_TRADE (CODNEG) values ('BBAS3');
Insert into TB_SWING_TRADE (CODNEG) values ('BBDC4');
Insert into TB_SWING_TRADE (CODNEG) values ('BBSE3');
Insert into TB_SWING_TRADE (CODNEG) values ('BRFS3');
Insert into TB_SWING_TRADE (CODNEG) values ('BVMF3');
Insert into TB_SWING_TRADE (CODNEG) values ('CCRO3');
Insert into TB_SWING_TRADE (CODNEG) values ('CIEL3');
Insert into TB_SWING_TRADE (CODNEG) values ('FIBR3');
Insert into TB_SWING_TRADE (CODNEG) values ('GGBR3');
Insert into TB_SWING_TRADE (CODNEG) values ('GOAU4');
Insert into TB_SWING_TRADE (CODNEG) values ('HYPE3');
Insert into TB_SWING_TRADE (CODNEG) values ('ITSA4');
Insert into TB_SWING_TRADE (CODNEG) values ('ITUB4');
Insert into TB_SWING_TRADE (CODNEG) values ('JBSS3');
Insert into TB_SWING_TRADE (CODNEG) values ('KROT3');
Insert into TB_SWING_TRADE (CODNEG) values ('QUAL3');
Insert into TB_SWING_TRADE (CODNEG) values ('RADL3');
Insert into TB_SWING_TRADE (CODNEG) values ('USIM5');
Insert into TB_SWING_TRADE (CODNEG) values ('VALE5');
Insert into TB_SWING_TRADE (CODNEG) values ('VIVT4');
Insert into TB_SWING_TRADE (CODNEG) values ('BEEF3');
Insert into TB_SWING_TRADE (CODNEG) values ('BRAP4');
Insert into TB_SWING_TRADE (CODNEG) values ('BRKM5');
Insert into TB_SWING_TRADE (CODNEG) values ('BRML3');
Insert into TB_SWING_TRADE (CODNEG) values ('CESP6');
Insert into TB_SWING_TRADE (CODNEG) values ('CMIG4');
Insert into TB_SWING_TRADE (CODNEG) values ('CPFE3');
Insert into TB_SWING_TRADE (CODNEG) values ('CSAN3');
Insert into TB_SWING_TRADE (CODNEG) values ('ECOR3');
Insert into TB_SWING_TRADE (CODNEG) values ('ELET6');
Insert into TB_SWING_TRADE (CODNEG) values ('EMBR3');
Insert into TB_SWING_TRADE (CODNEG) values ('EQTL3');
Insert into TB_SWING_TRADE (CODNEG) values ('ESTC3');
Insert into TB_SWING_TRADE (CODNEG) values ('FLRY3');
Insert into TB_SWING_TRADE (CODNEG) values ('GFSA3');
Insert into TB_SWING_TRADE (CODNEG) values ('GOLL4');
Insert into TB_SWING_TRADE (CODNEG) values ('IGTA3');
Insert into TB_SWING_TRADE (CODNEG) values ('KLBN11');
Insert into TB_SWING_TRADE (CODNEG) values ('LAME4');
Insert into TB_SWING_TRADE (CODNEG) values ('LIGT3');
Insert into TB_SWING_TRADE (CODNEG) values ('LREN3');
Insert into TB_SWING_TRADE (CODNEG) values ('MDIA3');
Insert into TB_SWING_TRADE (CODNEG) values ('MRFG3');
Insert into TB_SWING_TRADE (CODNEG) values ('MRVE3');
Insert into TB_SWING_TRADE (CODNEG) values ('MULT3');
Insert into TB_SWING_TRADE (CODNEG) values ('NATU3');
Insert into TB_SWING_TRADE (CODNEG) values ('ODPV3');
Insert into TB_SWING_TRADE (CODNEG) values ('PCAR4');
Insert into TB_SWING_TRADE (CODNEG) values ('PSSA3');
Insert into TB_SWING_TRADE (CODNEG) values ('RENT3');
Insert into TB_SWING_TRADE (CODNEG) values ('RAIL3');
Insert into TB_SWING_TRADE (CODNEG) values ('SBSP3');
Insert into TB_SWING_TRADE (CODNEG) values ('SMLE3');
Insert into TB_SWING_TRADE (CODNEG) values ('SMTO3');
Insert into TB_SWING_TRADE (CODNEG) values ('SUZB5');
Insert into TB_SWING_TRADE (CODNEG) values ('TIMP3');
Insert into TB_SWING_TRADE (CODNEG) values ('TRPL4');
Insert into TB_SWING_TRADE (CODNEG) values ('UGPA3');
Insert into TB_SWING_TRADE (CODNEG) values ('WEGE3');
Insert into TB_SWING_TRADE (CODNEG) values ('ABCB4');
Insert into TB_SWING_TRADE (CODNEG) values (null);
Insert into TB_SWING_TRADE (CODNEG) values ('ALPA4');
Insert into TB_SWING_TRADE (CODNEG) values ('ALSC3');
Insert into TB_SWING_TRADE (CODNEG) values ('ANIM3');
Insert into TB_SWING_TRADE (CODNEG) values ('BRPR3');
Insert into TB_SWING_TRADE (CODNEG) values ('BTOW3');
Insert into TB_SWING_TRADE (CODNEG) values ('CGAS5');
Insert into TB_SWING_TRADE (CODNEG) values ('CPLE6');
Insert into TB_SWING_TRADE (CODNEG) values ('CSMG3');
Insert into TB_SWING_TRADE (CODNEG) values ('CYRE3');
Insert into TB_SWING_TRADE (CODNEG) values ('DIRR3');
Insert into TB_SWING_TRADE (CODNEG) values ('DTEX3');
Insert into TB_SWING_TRADE (CODNEG) values ('ELPL4');
Insert into TB_SWING_TRADE (CODNEG) values ('EVEN3');
Insert into TB_SWING_TRADE (CODNEG) values ('EZTC3');
Insert into TB_SWING_TRADE (CODNEG) values ('FESA4');
Insert into TB_SWING_TRADE (CODNEG) values ('GRND3');
Insert into TB_SWING_TRADE (CODNEG) values ('HBOR3');
Insert into TB_SWING_TRADE (CODNEG) values ('HGTX3');
Insert into TB_SWING_TRADE (CODNEG) values ('JHFS3');
Insert into TB_SWING_TRADE (CODNEG) values ('LINX3');
Insert into TB_SWING_TRADE (CODNEG) values ('MGLU3');
Insert into TB_SWING_TRADE (CODNEG) values ('MILS3');
Insert into TB_SWING_TRADE (CODNEG) values ('MPLU3');
Insert into TB_SWING_TRADE (CODNEG) values ('MYPK3');
Insert into TB_SWING_TRADE (CODNEG) values ('POMO4');
Insert into TB_SWING_TRADE (CODNEG) values ('POSI3');
Insert into TB_SWING_TRADE (CODNEG) values ('QGEP3');
Insert into TB_SWING_TRADE (CODNEG) values ('RAPT4');
Insert into TB_SWING_TRADE (CODNEG) values ('RSID3');
Insert into TB_SWING_TRADE (CODNEG) values ('SHOW3');
Insert into TB_SWING_TRADE (CODNEG) values ('SULA11');
Insert into TB_SWING_TRADE (CODNEG) values ('TIET11');
Insert into TB_SWING_TRADE (CODNEG) values ('TOTS3');
Insert into TB_SWING_TRADE (CODNEG) values ('USIM3');
Insert into TB_SWING_TRADE (CODNEG) values ('VLID3');
Insert into TB_SWING_TRADE (CODNEG) values ('VVAR11');
